### ISSUE TITLE
Button State and Encoder value.

### ISSUE THREAD

**Issue by JacoFourie** [igorantolic/ai-esp32-rotary-encoder#1]
Hi.

I am testing this lib and have some questions.

1) I only get 2 states (BUT_DOWN) and (BUT_RELEASED) when do I get BUT_PUSHED ?
2) The value increases with more than 1 value wit the encoder I have. On the Arduino lib I can set the click count. It has to be 4 with this encoder I have. How do I set it with this lib so I get single increments ?

**Comment by JacoFourie** [comment]
I use this library on Arduino. https://github.com/soligen2010/encoder
The Clicked, DoubleClicked, Held and Released works well. What is the chance of getting something like that ?

**Comment by igorantolic** [comment]
Go for it.
Make a fork of my solution, modify, test, *share*...
