### ISSUE TITLE
Questions about behaviours

### ISSUE THREAD

**Issue by Titibo26** [igorantolic/ai-esp32-rotary-encoder#12]
Hi, I have some questions about how the library works : 

- rotaryEncoder.encoderChanged(); --> if i reset it, does the DELTA is between the last value and 0 (or reset value ?)

- rotaryEncoder.setBoundaries(1,4,true); 
What are the maximum boundaries we can use ? (-10 000, 10 000) is working but i can't put a bigger limit. Can we use it without limit ? I tried some changes but i can get it working without seting boundaries.

Thanks,

TD

**Comment by igorantolic** [comment]
a) calling rotaryEncoder.encoderChanged() will clear the change

b) you can use it now with large boundaries since acceleration is added. Try version 1.1
