### ISSUE TITLE
INPUT_PULLUP not defined

### ISSUE THREAD

**Issue by EsserPrototyping** [igorantolic/ai-esp32-rotary-encoder#13]
I´m not sure if this is a misunderstanding by myself, but when i connect an incremental encoder with the middle pin as GND and no pushbutton, i need to define the A+B-pins to be INPUT_PULLUP. (Which makes sense, otherwise they are floating)
Is this a bug, or do most of the people use external pullups? Or is the button VCC-pin involved in this?
I´m using a esp32doit board.

**Comment by igorantolic** [comment]
I used module not encoder only. Currently I am not at home to check but may
be that module has these resistors on board. But if you use it directly
modify to pullup.

sub, 27. srp 2019. 17:33 EsserPrototyping <notifications@github.com> je
napisao:
