### ISSUE TITLE
lambda function not in IRAM

### ISSUE THREAD

**Issue by paul303** [igorantolic/ai-esp32-rotary-encoder#14]
In the example "Esp32RotaryEncoderBasics.ino" the lambda function for calling the ISR is not put into IRAM.

`rotaryEncoder.setup([]{rotaryEncoder.readEncoder_ISR();});`

Having the **complete** ISR call in IRAM is something I have painfully learned. My solution is to wrap the call in a plain function like

`void IRAM_ATTR readEncoderWrapper_ISR(){
rotaryEncoder.readEncoder_ISR();
}`

and set the library up with

`rotaryEncoder.setup(readEncoderWrapper_ISR);`

[This discussion](https://github.com/esp8266/Arduino/pull/5780) helped me to understand.

I hope this helps.

p.s. thanks for your ai-esp32-rotary-encoder library!

**Comment by igorantolic** [comment]
Would you improve the code and then I can merge.
Obviously you know how so we can improve.

**Comment by ril3y** [comment]
@paul303 can you share your implementation?

**Comment by stevesch** [comment]
I encountered the same-- example still has this flaw.  Just do not use the lambda.  Use a separate function defined with IRAM_ATTR:

```
void IRAM_ATTR readEncoderISR()
{
  rotaryEncoder.readEncoder_ISR();
}

void setup()
{
  rotaryEncoder.setup(readEncoderISR);
}
```

**Comment by igorantolic** [comment]
All examples are updated to include the same solution. Additionally, button functions changed.
