### ISSUE TITLE
Error compiling Esp32RotaryEncoder.ino for ESP8266 

### ISSUE THREAD

**Issue by 3APEBO** [igorantolic/ai-esp32-rotary-encoder#15]
Hello everybody,
Example sketch compiles without any problems for ESP32 boards, but gives the following error for ESP8266 boards (pin definitions are modified appropriately) : 

Arduino: 1.8.10 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\Andre\Documents\Arduino\ESP8266_RotaryEncoder_test\ESP8266_RotaryEncoder_test.ino:1:0:

C:\Users\Andre\Documents\Arduino\libraries\ai-esp32-rotary-encoder-master\src/AiEsp32RotaryEncoder.h:31:2: error: 'portMUX_TYPE' does not name a type

  portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;

Multiple libraries were found for "AiEsp32RotaryEncoder.h"
 Used: C:\Users\Andre\Documents\Arduino\libraries\ai-esp32-rotary-encoder-master
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Can somebody help?

**Comment by fgolemo** [comment]
Got the same issue.

**Comment by AlbanT** [comment]
Same issue here :(

```
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src/AiEsp32RotaryEncoder.h:30:2: error: 'portMUX_TYPE' does not name a type
  portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;
  ^
In file included from .pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp:5:0:
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.h:30:2: error: 'portMUX_TYPE' does not name a type
  portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;
  ^
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp: In member function 'void AiEsp32RotaryEncoder::readEncoder_ISR()':
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp:10:33: error: 'class AiEsp32RotaryEncoder' has no member named 'mux'
  portENTER_CRITICAL_ISR(&(this->mux));
                                 ^
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp:10:37: error: 'portENTER_CRITICAL_ISR' was not declared in this scope
  portENTER_CRITICAL_ISR(&(this->mux));
                                     ^
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp:71:25: error: 'mux' was not declared in this scope
  portEXIT_CRITICAL_ISR(&mux);
                         ^
.pio\libdeps\d1_mini\Ai Esp32 Rotary Encoder\src\AiEsp32RotaryEncoder.cpp:71:28: error: 'portEXIT_CRITICAL_ISR' was not declared in this scope
  portEXIT_CRITICAL_ISR(&mux);
                            ^
*** [.pio\build\d1_mini\src\main.cpp.o] Error 1
*** [.pio\build\d1_mini\lib749\Ai Esp32 Rotary Encoder\AiEsp32RotaryEncoder.cpp.o] Error 1
```

**Comment by igorantolic** [comment]
You should read the name of the library :))) Perhaps it is ESP32? Kidding... 
Some good people made a contribution for ESP8266, while some other good people improved ESP32.
Would be nice you can contribute making it again compatible for all devices.

**Comment by AlbanT** [comment]
@igorantolic I understand but I think this should be mentioned here as the readme states: **Arduino Esp32 / _ESP8266_ MULTIPLE Encoder Library** Maybe update the readme mentioning this issue!?
Unfortunately I wouldn't know where to start to fix this issue so for my ESP8266 I'll look for an alternative but for ESP32 it does seem to work (I uploaded the code and that worked bit didn't do the wiring yet so couldn't really test).

**Comment by igorantolic** [comment]
As you can find out seems like change "Encoder library now supports multiple instances of encoders"
improved promised in title, on the expense of compatibility.

https://github.com/igorantolic/ai-esp32-rotary-encoder/commit/48372435a898eb7bda7e1cc6e8875c88b63d1cdd#diff-
8c15260b6e586b781623a9fa7818e635

Might happen the the author of the change probably didn't take into consideration checking compatibility, nor updating the documentation.
To be honest I didn't work on code for so long (typical lack of time issue) so if you would like to contribute community will be thankful.

I said I was kidding regarding the leading remark. I understand your point of view.

**Comment by igorantolic** [comment]
Added support for ESP8266
