### ISSUE TITLE
Guru Meditation Error: when rotating fast

### ISSUE THREAD

**Issue by FrankHovis** [igorantolic/ai-esp32-rotary-encoder#22]
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x400d0b3c  PS      : 0x00060034  A0      : 0x40087284  A1      : 0x3ffbff50
A2      : 0x0000000d  A3      : 0x3ffc1afc  A4      : 0x00000000  A5      : 0x00002000
A6      : 0x00042098  A7      : 0x3ffb8b88  A8      : 0x8008111c  A9      : 0x00000001
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x8008f099  A13     : 0x3ffb1ad0
A14     : 0x00000000  A15     : 0x3ffb1b0c  SAR     : 0x00000011  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000
Core 1 was running in ISR context:
EPC1    : 0x4008f1b4  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x400d0b3c

**Comment by igorantolic** [comment]
IT works on my esp32

pet, 9. tra 2021. u 22:49 Frank Hovis ***@***.***> napisao je:

**Comment by stevesch** [comment]
See this issue-- I think it's the same:
https://github.com/igorantolic/ai-esp32-rotary-encoder/issues/14

don't use the lambda like in the example-- define a separate function with IRAM_ATTR attribute.

You may not hit this issue unless your sketch is larger or doing a bunch of work.

**Comment by igorantolic** [comment]
Soved. See: https://github.com/igorantolic/ai-esp32-rotary-encoder/issues/14
