### ISSUE TITLE
Using rotaryEncoder.setup() without a Button ISR: Misunderstanding, or bug?

### ISSUE THREAD

**Issue by twr140** [igorantolic/ai-esp32-rotary-encoder#27]
I am new to arduino / ESP32, and have only basic understanding of C / C++, so it's possible I'm doing something wrong or unnecessary, but looking to the code in AiEsp32RotaryEncoder.h it seems that the rotaryEncoder.setup() function has 2 versions (function override?):

```
void setup(void (*ISR_callback)(void));	
void setup(void (*ISR_callback)(void), void (*ISR_button)(void));
```

However, in AiEsp32RotaryEncoder.cpp there is only a single function definition for the setup routine:

```
void AiEsp32RotaryEncoder::setup(void (*ISR_callback)(void), void (*ISR_button)(void))
{	attachInterrupt(digitalPinToInterrupt(this-&gt;encoderAPin), ISR_callback, CHANGE);	
        attachInterrupt(digitalPinToInterrupt(this-&gt;encoderBPin), ISR_callback, CHANGE);	 
        attachInterrupt(digitalPinToInterrupt(this-&gt;encoderButtonPin), ISR_button, RISING);
}
```
Without any changes, the supplied examples all worked successfully - but these all call a button ISR.  However, in my own program if I tried to call:

`rotaryEncoder.setup( [] { Encoder.readEncoder_ISR(); } );`

(i.e. no button ISR, just the encoder ISR), the code failed to compile, with the generic error "unable to compile for Adafruit ESP32 Feather"

I then changed the code in AiEsp32RotaryEncoder.cpp to create 2 versions of the setup function, one without the button ISR, and the other as it was originally, like this:

```
void AiEsp32RotaryEncoder::setup(void (*ISR_callback)(void))
{
	attachInterrupt(digitalPinToInterrupt(this->encoderAPin), ISR_callback, CHANGE);
	attachInterrupt(digitalPinToInterrupt(this->encoderBPin), ISR_callback, CHANGE);
}

void AiEsp32RotaryEncoder::setup(void (*ISR_callback)(void), void (*ISR_button)(void))
{
	attachInterrupt(digitalPinToInterrupt(this->encoderAPin), ISR_callback, CHANGE);
	attachInterrupt(digitalPinToInterrupt(this->encoderBPin), ISR_callback, CHANGE);
	attachInterrupt(digitalPinToInterrupt(this->encoderButtonPin), ISR_button, RISING);
}

```
The code now compiles successfully, and I can call the setup routine either with or without an ISR for the button.

Is what I have done correct, or have I misunderstood something due to my limited knowledge of C / C++ ?

(I also don't know how to go about submitting this as a code change to this repository, so if these changes are correct, can someone please make the required changes? Thank you)

**Comment by igorantolic** [comment]
New version has now the same. One argument version is preferred and all examples now updated to use that version with different solution for button click.
