### ISSUE TITLE
Reverse direction

### ISSUE THREAD

**Issue by sschueller** [igorantolic/ai-esp32-rotary-encoder#29]
Hi, thanks for this library, it works quite well.

Is it possible to reverse the direction? Right now I turn the encoder clockwise the value goes down. I would like to have it go up instead when turning clockwise. I am using the Number-select example.

**Comment by igorantolic** [comment]
if you select numbers between 0 and 100
then use value = 100-value

so when raising like 80 result is 20
and lower 20 result is 80

Or just buy correctly connected rotary encoder
