### ISSUE TITLE
changing ( .setEncoderValue  ) trigger s (   .encoderChanged();  ) to  ( -   minus state )

### ISSUE THREAD

**Issue by ashrafkawasmi** [igorantolic/ai-esp32-rotary-encoder#30]
hello 

is this by default like this ?

it is making me crazy 

each time i change the the encoder value - it trigers the encoder to minus 

thank oyu

**Comment by igorantolic** [comment]
Which example file did you use?

**Comment by igorantolic** [comment]
Please see example Multi-select.ino
Seems to work properly.

**Comment by igorantolic** [comment]
In case you dont provide more information I will close this ticket

**Comment by igorantolic** [comment]
Closed due to lack of details
