### ISSUE TITLE
readButton_ISR

### ISSUE THREAD

**Issue by dirtmover** [igorantolic/ai-esp32-rotary-encoder#37]
readButton_ISR looks like a work in progress. Are you planning to work on this feature?

**Comment by igorantolic** [comment]
Some contributors did this. Personally, I am taking a whole different approach since often I want to distinguish short clicks and long press. Also, I care a lot about debouncing.

In short - I got no plans to continue working on this.

**Comment by igorantolic** [comment]
That was question which is answered so issue is closed
