### ISSUE TITLE
Support for bare bones rotary encoder

### ISSUE THREAD

**Issue by Grimwig** [igorantolic/ai-esp32-rotary-encoder#38]
Hi, I see that someone has raised a pull request for an issue I've been having. Might I respectfully request that you add a flag such that the mode of the input pins can be chosen between PULLUP and PULLDOWN. Currently your library assumes a KY-040 style breakout board or external pullup resistors. This new feature would allow those MCUs (e.g. ESP32) with software-enabled pullup/pulldown functions to use bare rotary encoders without the need for physical pullup resistors. Thanks for a great library!

**Comment by igorantolic** [comment]
Changes merged
