### ISSUE TITLE
not using encoderButtonPin

### ISSUE THREAD

**Issue by zhivko** [igorantolic/ai-esp32-rotary-encoder#4]
If I am not using encoderButtonPin why not initialize it only if pin no is >-1 like it is case for encoderVccPin:

if (encoderVccPin >= 0) {
		pinMode(encoderVccPin, OUTPUT);	digitalWrite(encoderVccPin, 1);//Vcc for encoder 
}

so something like:

if (encoderButtonPin>= 0) {
pinMode(encoderButtonPin, INPUT_PULLUP);
}

does it sound reasonable?

**Comment by igorantolic** [comment]
Yes you can do that.

pet, 20. srp 2018. 22:24 zhivko <notifications@github.com> je napisao:
