### ISSUE TITLE
For ESP32 - Issue with the "Circling" Option

### ISSUE THREAD

**Issue by VonHirsch** [igorantolic/ai-esp32-rotary-encoder#40]
This library is a great idea (boundaries & acceleration) and thank you!  However on ESP32 there are bugs when using the "circleValues" feature (when max go to min and vice versa.)  I would like to try and debug and fix, but when looking at the code, my opinion it needs a whole re-write, and I'm not up to that at the moment unfortunately.

I'm switching to something like this, and adding the other features as needed:
https://github.com/buxtronix/arduino/tree/master/libraries/Rotary

**Comment by igorantolic** [comment]
Not šute what was the issue with Circle values but as I remember example
worked

Have you checked all examples using this?

Circle calues should be very simple and usually used on menu selections

In some other use cases that are not covered we should first wrote use
cases and then do the fix to Match the expectations

I understand that many features cause many scenarios so some might not be
tested when using some combinations

sub, 28. svi 2022. u 15:20 VonHirsch ***@***.***> napisao je:

**Comment by VonHirsch** [comment]
Sure, happy to provide output from the examples.  The only thing I changed in the examples was PIN B to 19 and Encoder Steps to 2 for my circuit and hardware:

```
#define ROTARY_ENCODER_B_PIN 19
#define ROTARY_ENCODER_STEPS 2
```

**Details:**

- Hardware: ESP32_Devkitc_V4
- Encoders: https://www.aliexpress.com/item/3256802939670003.html

Here's the output of the "**Esp32RotaryEncoderBasics.ino**" sketch.  Everything working perfectly, Notice I get only one change in value per click of the encoder:

**One Line = One Encoder Click**
![image](https://user-images.githubusercontent.com/3280180/170869208-372c35c7-5c7e-4d13-b584-2828c827948f.png)

Now here's the output of "**Multi-select.ino**" on the same exact hardware and encoder setup.  I've enabled "Show Timestamp" in the Arduino output and put a red box around those with the same timestamp where I get more than one change when turning the encoder one click:

**Multiple Changes per Encoder Click (In Red Squares)**
![image](https://user-images.githubusercontent.com/3280180/170869433-71b43597-af48-44f6-8d1b-b6c001a88d4a.png)

**Conclusion:** 
When the "Circling" option is enabled there are often multiple changes per click of the encoder.

**Comment by igorantolic** [comment]
is it the same when using
#define ROTARY_ENCODER_STEPS 4

does the change of this parameter to values 1,2 and 4 does any difference?

It sounds like doubling the param should help

**Comment by VonHirsch** [comment]
If I define steps as 4 then the encoder only changes value every other click

**Comment by igorantolic** [comment]
ok so for you the best. value is 2

try setAcceleration(0) or (1)
using
rotaryEncoder.setAcceleration(acceletation);

**Comment by VonHirsch** [comment]
I thought acceleration might be causing the issue, but when I disable it with setAcceleration(0) still the same issue.

**Comment by igorantolic** [comment]
I am on a vacation and unable to try this
If you find a solution let me know
It is not expected that if numeric value changes normally that it will
behave differently in this example

**Comment by VonHirsch** [comment]
sure no problem.  I looked for an obvious bug in the code but couldn't find it but I hope you can!  Thanks again for the library.

**Comment by VonHirsch** [comment]
sure no problem.  I looked for an obvious bug in the code but couldn't find
it but I hope you can!  Thanks again for the library.

**Comment by igorantolic** [comment]
Fixed. (Was a bit complex due to the logic)
