### ISSUE TITLE
gpio: gpio_set_level(226): GPIO output gpio_num error

### ISSUE THREAD

**Issue by ryuenma** [igorantolic/ai-esp32-rotary-encoder#41]
Hi, i would like to thank you for providing this library.

I'm currently using it for my project. I'm using wokwi first to code as to grasp what i'm working on without needing to reflash my esp32 many times. everytime i ran the code, i would get this error below:

`E (167) gpio: gpio_set_level(226): GPIO output gpio_num error`

i've asked the wokwi discord, and someone there said (directly quoting them):
`OK, it should be harmless. The docs for the library suggest setting the encoder Vcc pin to -1 when the encoder is connected directly to the ESP's Vcc. But this pin number is stored in an unsigned variable, so when https://github.com/igorantolic/ai-esp32-rotary-encoder/blob/master/src/AiEsp32RotaryEncoder.cpp#L199-L203 that code checks to see if it is >=0 the answer is always true. It's just a warning that the library tried to set pin 255, and there isn't a pin 255.`

at first it would boot just fine, but it seems like after doing everything in the void setup the web started chugging to only around 20% speed. seems like something is wrong with my code

**Comment by Frank-Bemelman** [comment]
Actually ran into the same warning today. The wokwi comment you found is correct. The encoderVccPin value defaults to -1 when not provided, or you can provide it with -1 yourself when setting up AiEsp32RotaryEncoder(...). 

I can imagine you want to get rid of the warning (like I do too).  You could set a spare pin for encoderVccPin. Or repair the code in AiEsp32RotaryEncoder, line 199.

I changed it to:
	if (this->encoderVccPin < 255)

That made the warning dissapear in my situation.  But as said by the wokwi contributor, it's not a big deal. 

Cheers,
Frank

**Comment by ryuenma** [comment]
Alright, thanks frank for the answer!

i'll make do with the workaround for now, as it's nothing fatal.

**Comment by Belleson** [comment]
I also see this warning and the same bug exists at the next if statement line 207. As the highest GPIO pin is 39, I changed to

if (this->encoderVccPin < 40)
