### ISSUE TITLE
imported the code to vs code platformio

### ISSUE THREAD

**Issue by cnc4less** [igorantolic/ai-esp32-rotary-encoder#53]
On compile, i get this error
no declaration matches 'AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)'
how to fix it  , regards

**Comment by cnc4less** [comment]
fixed by making it like this

public:
	AiEsp32RotaryEncoder(
		uint8_t encoderAPin = AIESP32ROTARYENCODER_DEFAULT_A_PIN,
		uint8_t encoderBPin = AIESP32ROTARYENCODER_DEFAULT_B_PIN,
		uint8_t encoderButtonPin = AIESP32ROTARYENCODER_DEFAULT_BUT_PIN,
		uint8_t encoderVccPin = AIESP32ROTARYENCODER_DEFAULT_VCC_PIN,
		uint8_t encoderSteps = AIESP32ROTARYENCODER_DEFAULT_STEPS);

**Comment by igorantolic** [comment]
Great thanks for info
