### ISSUE TITLE
Encoder button is not working

### ISSUE THREAD

**Issue by arslan437** [igorantolic/ai-esp32-rotary-encoder#54]
My encoder has a pull-down resistor on the PCB. Is there a way to make pull down button work with this library.

**Comment by igorantolic** [comment]
in AiEsp32RotaryEncoder.cpp
there is logic

	if (this->encoderButtonPin >= 0)
	{
		pinMode(this->encoderButtonPin, INPUT_PULLUP);
	}

You should set encoderButtonPin  to a negative value like encoderButtonPin =-1
Then use your own logic for a button (treat is as a normal button and do the logic)
