### ISSUE TITLE
Compilation errors with examples

### ISSUE THREAD

**Issue by NegativCut** [igorantolic/ai-esp32-rotary-encoder#56]
Hi, I am trying out this library but a few errors persist during compilation. Everything is left untouched in the examples, including pin assignments.
I am compiling for ESP32 Dev Module.

`Compiling sketch...
In file included from G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:11:
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.h:53:32: warning: left shift of negative value [-Wshift-negative-value]
  long _minEncoderValue = -1 << 15;
                                ^~

G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp: In member function 'void AiEsp32RotaryEncoder::begin()':
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:199:26: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  if (this->encoderVccPin >= 0)
      ~~~~~~~~~~~~~~~~~~~~^~~~

G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:207:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  if (this->encoderButtonPin >= 0)
      ~~~~~~~~~~~~~~~~~~~~~~~^~~~

G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp: In member function 'ButtonState AiEsp32RotaryEncoder::readButtonState()':
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:220:14: error: unused variable '_buttonState' [-Werror=unused-variable]
  ButtonState _buttonState = buttonState;
              ^~~~~~~~~~~~

cc1plus.exe: some warnings being treated as errors
Using library Ai_Esp32_Rotary_Encoder at version 1.4 in folder: G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder 
exit status 1
Error compiling for board ESP32 Dev Module.
`

Are these problems with the library, or some upload setting I have?

**Comment by igorantolic** [comment]
I can see someone changed int to unsigned int vccencoderpin

Until I find some spare time if you know you can modify the code

If you dont need negativne values minencoder can be 0

So with 2 minute change you can fix it
And when I find some time I have to recheck all examples

Some people ask for change and I guess I trusted them more than I should


pon, 17. tra 2023. u 05:49 NegativCut ***@***.***> napisao je:

**Comment by NegativCut** [comment]
okay, that cleared up some of it, thanks. Still got the following errors reported at compilation;

G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp: In member function 'void AiEsp32RotaryEncoder::begin()':
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:207:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  if (this->encoderButtonPin >= 0)
      ~~~~~~~~~~~~~~~~~~~~~~~^~~~
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp: In member function 'ButtonState AiEsp32RotaryEncoder::readButtonState()':
G:\Dropbox\CODE\libraries\Ai_Esp32_Rotary_Encoder\src\AiEsp32RotaryEncoder.cpp:220:14: error: unused variable '_buttonState' [-Werror=unused-variable]
  ButtonState _buttonState = buttonState;
              ^~~~~~~~~~~~

**Comment by igorantolic** [comment]
if (this->encoderButtonPin >= 0)

replace with
if (true) or if (false)

remove line
ButtonState _buttonState = buttonState;

**Comment by igorantolic** [comment]
Corrected - returned to be int again as designed initially.
Should work now again
