### ISSUE TITLE
`encoderVccPin` declared as `uint32_t` so `encoderVccPin >= 0` is always true

### ISSUE THREAD

**Issue by starlino** [igorantolic/ai-esp32-rotary-encoder#57]
this cause ESP32 error to be displayed when `encoderVccPin == -1`

https://github.com/igorantolic/ai-esp32-rotary-encoder/blob/3d2fadd360ff613fe6258735b5eda75da2274a99/src/AiEsp32RotaryEncoder.cpp#L199

maybe make `encoderVccPin` int32_t, same for the `encoderButtonPin`

**Comment by igorantolic** [comment]
Corrected - returned to be int again as designed initially.
Should work now again

**Comment by igorantolic** [comment]
Corrected - returned to be int again as designed initially.
Should work now again
