### ISSUE TITLE
push-button works on release not press

### ISSUE THREAD

**Issue by billbill100** [igorantolic/ai-esp32-rotary-encoder#58]
Using the basic sketch,
the push-button does not register as pushed until AFTER it has been released.

I need it to register the push & whilst still pushed, go off and do something....

**Comment by igorantolic** [comment]
Use manual logic - your own solution
You can find so many solutions on internet and ChatGPS for Arduino button

Just on each loop check and remember the state of the button (bool
lastStateWasOn, lastStateChangedAt (use millis() function))
Then do the logic

There is absolutely no strings attached - so you can completely ignore the
logic in library

**Comment by igorantolic** [comment]
in this version try changing true/false for
    rotaryEncoder.isButtonPulldown = false;
	  rotaryEncoder.areEncoderPinsPulldownforEsp32 = true;
