### ISSUE TITLE
ESP32-S3: Warning Invalid Pin Selected

### ISSUE THREAD

**Issue by Deadeye5589** [igorantolic/ai-esp32-rotary-encoder#61]
Hello,

it seems that there is some trouble when defining the ROTARY_ENCODER_VCC_PIN to -1 on a ESP32-S3 chipset. 
In this case the following message is reported back via UART interface. 

[  5475][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected
E (5242) gpio: gpio_set_level(226): GPIO output gpio_num error

As a workaround I can define the VCC Pin to be attached to an unused pin.

**Comment by igorantolic** [comment]
Use the last version from github and it will work
