### ISSUE TITLE
compile error on esp32

### ISSUE THREAD

**Issue by McMornan** [igorantolic/ai-esp32-rotary-encoder#62]
Hi,

I am using esp32 dev board. In file AiEsp32RotaryEncoder.cpp the line 255 should read like that: 

pinMode(this->encoderButtonPin,isButtonPulldown? INPUT_PULLDOWN:INPUT_PULLUP);

There was a comma instead, which lead to a compile error.

cheers,
Lars

**Comment by igorantolic** [comment]
Thanks, man!
I had no ESP32 so didn't test properly.
Fixed!
