### ISSUE TITLE
Arduino Nano ESP32 encoder pins

### ISSUE THREAD

**Issue by msilveus** [igorantolic/ai-esp32-rotary-encoder#66]
First let my say that I like your code and it works but I have this one issue that plagued me.

Not sure what is going on but it doesn't matter what pins I assign for the encoder pins they are not responsive even when I set 
   rotaryEncoder.areEncoderPinsPulldownforEsp32=false; 

Or if I hard code INPUT_PULLUP in the AiEsp32RotaryEncoder.cpp file
	pinMode(this->encoderAPin, INPUT_PULLUP);
	pinMode(this->encoderBPin, INPUT_PULLUP);
I have still have to attach external pullup resistors for code to work properly. 

When I probe the GPIO pin there is no pullup voltage on the pin. The button pin is fine and has pullup voltage even when I move it to where the encoder pins were. It makes no sense as to why this only affects the encoder pins.

Regards,
Mike

**Comment by igorantolic** [comment]
That works for esp32
Nano has no pullups I think so external are required
