### ISSUE TITLE
ESP8266 Compile Error

### ISSUE THREAD

**Issue by galagen8** [igorantolic/ai-esp32-rotary-encoder#69]
### During compiling for ESP8266 I got this issue:

f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.cpp:135:1: error: no declaration matches 'AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)'
  135 | AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(uint8_t encoder_APin, uint8_t encoder_BPin, uint8_t encoder_ButtonPin, uint8_t encoder_VccPin, uint8_t encoderSteps)
      | ^~~~~~~~~~~~~~~~~~~~
In file included from f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.cpp:11:
f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.h:29:7: note: candidates are: 'constexpr AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(AiEsp32RotaryEncoder&&)'
   29 | class AiEsp32RotaryEncoder
      |       ^~~~~~~~~~~~~~~~~~~~
f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.h:29:7: note:                 'constexpr AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(const AiEsp32RotaryEncoder&)'
f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.h:67:2: note:                 'AiEsp32RotaryEncoder::AiEsp32RotaryEncoder(uint8_t, uint8_t, uint8_t, int8_t, uint8_t)'
   67 |  AiEsp32RotaryEncoder(
      |  ^~~~~~~~~~~~~~~~~~~~
f:\DG\Arduino\libraries\ai-esp32-rotary-encoder-master\src\AiEsp32RotaryEncoder.h:29:7: note: 'class AiEsp32RotaryEncoder' defined here
   29 | class AiEsp32RotaryEncoder
      |       ^~~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

### But with esp32 it compiles without any issues.
Could you help me to show me right direction how to fix the mistake?

**Comment by igorantolic** [comment]
Fixed
