### ISSUE TITLE
Typo in current code

### ISSUE THREAD

**Issue by ttump** [igorantolic/ai-esp32-rotary-encoder#7]
Hi, the current library isn't working at the moment because the interrupt routine is pointing to array "enc_states" (which it probably used to be) but the header file is using "enc_state". Also the example is not calling the interrupt setup routine.

**Comment by igorantolic** [comment]
Can you please correct and send pull request. Thanks.

**Comment by telanoc** [comment]
I think the reset() method should also set the lastReadEncoder0Pos value, otherwise the next time you call encoderChanged() , you read the negative of how much you reset it by.  If you're doing your own calculations based on the delta change, it messes things up.

**Comment by igorantolic** [comment]
Will you do the change of code?

**Comment by telanoc** [comment]
Sorry, I already switched to a different encoder library (ESP32Encoder by madhephaestus) and don't have your code on my development system any more.  (also, sorry to the OP - my comment was supposed to be a new issue, not a derailment of yours)

**Comment by igorantolic** [comment]
I am glad you solved your problem.

**Comment by igorantolic** [comment]
V 1.1 working now
