### ISSUE TITLE
setValue for AiEsp32RotaryEncoderNumberSelector is not working anymore

### ISSUE THREAD

**Issue by bardoo** [igorantolic/ai-esp32-rotary-encoder#74]
Hi, and thanks for this nice library. I tried upgrading from 1.4 to 1.6, but it seems that the `setValue()` on the AiEsp32RotaryEncoderNumberSelector doesn't do anything anymore. It compiles and everything seems fine, but it just doesn't update with the new value. Let me know if you need more info.

**Comment by kr4fty** [comment]
Aren't you referring to the setEncoderValue() function?, which sets the encoder counter to the value

void setEncoderValue(long newValue);

**Comment by DanielPineiroCalvo** [comment]
Hi! I also I´m looking to modify the encoder counter value, but the funtion setEncoderValue(long newValue) does not compile. In my project the encoder send OSC values, but also can be change by OSC incoming menssages.  Thanks for your help!

**Comment by DanielPineiroCalvo** [comment]
Hi again!
 I got it, the function is rotaryEncoder.reset(newValue)

Thanks four you work in this great library!!!
