### ISSUE TITLE
Using multiple "encoder number selectors" with one encoder

### ISSUE THREAD

**Issue by willdatrill2007** [igorantolic/ai-esp32-rotary-encoder#77]
Hello, great work on your library. If possible, can you post an example code to accomplish this if it's possible? I'm trying to assign a number selector for each of three values but when I adjust one value it affects the rest.

**Comment by igorantolic** [comment]
you should have 1 value rotary adjust lets call it "R"
but then additionally 3 values for real values lats call them "A" "B " "C"

when you "switch" to the next value you are setting, just store R-> A
then you read from B to R

next "switch" will store R->B and then read from C to R

Often when switching I also modify the range limits

this way lets say A is temperature in range 16-28
B is humidity in range 70-100
and C is ....

Then when switching additionally adjust range

Example you can find in example folder of the lib
