### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yanxke** [igorantolic/ai-esp32-rotary-encoder#81]
Is it possible to publish a new release with the latest updates, for example the ESP32 pull down option in the constructor?  Thanks.

**Comment by kr4fty** [comment]
Also on platformio

[igorantolic/Ai Esp32 Rotary Encoder](https://registry.platformio.org/libraries/igorantolic/Ai%20Esp32%20Rotary%20Encoder)

**Comment by igorantolic** [comment]
done, waiting for changes to be recognized and refreshed

**Comment by yanxke** [comment]
Thank you!
